apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  namespace: nfs-system
allowVolumeExpansion: true
mountOptions:
- vers=3
provisioner: cluster.local/nfs-server-provisioner-nfs-server-provisioner
reclaimPolicy: Delete
