apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component
namespace: nfs-system
commonLabels:
  name: nfs-server-provisioner
  component: volume-provisioner
  part-of: kubernetes
resources:
- nfs-namespace.yaml
- nfs-inventory.yaml
- inflated
- default-nfs-storage-class.yaml
