apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps_v1_deployment_local-path-provisioner.yaml
- rbac.authorization.k8s.io_v1_clusterrole_local-path-provisioner-role.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_local-path-provisioner-bind.yaml
- v1_configmap_local-path-config.yaml
- v1_serviceaccount_local-path-provisioner-service-account.yaml
