apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  name: metallb

namespace: metallb

resources:
  - inflated
  - namespace.yaml
  - layer2-config.yaml
  - memberlist-secret.yaml

