apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: metallb

namespace: metallb

resources:
  - namespace.yaml
  - inventory.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.9.5/manifests/metallb.yaml
  - layer2-config.yaml
  - memberlist-secret.yaml

