apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

commonLabels:
  name: metallb

namespace: metallb

resources:
  - namespace.yaml
  - inflated
  - layer2-config.yaml
  - memberlist-secret.yaml

