kind: Role # Source: csi-hostpath/templates/snapshot-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: csi-system
  name: snapshot-controller-leaderelection
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
