kind: RoleBinding # Source: csi-hostpath/templates/snapshot-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snapshot-controller-leaderelection
  namespace: csi-system
subjects:
- kind: ServiceAccount
  name: snapshot-controller
  namespace: csi-system
roleRef:
  kind: Role
  name: snapshot-controller-leaderelection
  apiGroup: rbac.authorization.k8s.io
