kind: StatefulSet # Source: csi-hostpath/templates/snapshot-controller.yaml
apiVersion: apps/v1
metadata:
  name: snapshot-controller
  namespace: csi-system
spec:
  serviceName: "snapshot-controller"
  replicas: 1
  selector:
    matchLabels:
      app: snapshot-controller
  template:
    metadata:
      labels:
        app: snapshot-controller
    spec:
      serviceAccount: snapshot-controller
      containers:
      - name: snapshot-controller
        image: "k8s.gcr.io/sig-storage/snapshot-controller:v3.0.0"
        imagePullPolicy: IfNotPresent
        args:
        - "--v=5"
        - "--leader-election=false"
