apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-manifest-generator
  annotations:
    config.kubernetes.io/function: |
      container:
        image: mgoltzsche/khelm:latest
        network: true
    config.kubernetes.io/local-config: "true"
data:
  repository: https://speedwing.github.io/csi-hostpath-helm
  chart: csi-hostpath
  version: 0.0.6
  name: csi-hostpath
  namespace: csi-system
  outputPath: inflated/
  # ---
  # apiVersion: v1
  # kind: ConfigMap
  # metadata:
  #   name: render-kustomization
  #   annotations:
  #     config.kubernetes.io/function: |
  #       container:
  #         image: mgoltzsche/kustomizr:0.1
  #         network: true
  #     config.kubernetes.io/local-config: 'true'
  # data:
  #   path: ./
  #   outputPath: ./static/generated-manifest.yaml
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: render-kustomization
#   annotations:
#     config.kubernetes.io/function: |
#       container:
#         image: mgoltzsche/kustomizr:0.1
#         network: true
#     config.kubernetes.io/local-config: 'true'
# data:
#   path: ./
#   outputPath: ./static/generated-manifest.yaml
