apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csi-system
commonLabels:
  name: csi-hostpath
  component: volume-provisioner
  part-of: kubernetes
resources:
- csi-system-inventory.yaml
- csi-system-namespace.yaml
components:
- kustomization
