apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: csi-system
commonLabels:
  name: csi-hostpath
  component: volume-provisioner
  part-of: kubernetes
resources:
- ../inflated
- default-storage-class.yaml
- nos-workspace-storage-class.yaml
patchesStrategicMerge:
- replace-microk8s-kubelet-var-dirs.yaml
