apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  name: csi-hostpath
namespace: csi-hostpath
resources:
- namespace.yaml
- inflated
patchesStrategicMerge:
- replace-microk8s-kubelet-var-dirs.yaml 
