apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: csi-hostpath
commonLabels:
  name: csi-hostpath
resources:
- inflated
- namespace.yaml
patchesStrategicMerge:
- replace-microk8s-kubelet-var-dirs.yaml 
