apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csi-hostpath
commonLabels:
  name: csi-hostpath
  component: volume-provisioner
  part-of: kubernetes
resources:
- inventory.yaml
- namespace.yaml
components:
- kustomization
