apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  name: metrics-server
  component: monitoring
  part-of: kubernetes
namespace: kube-system
resources:
- inventory.yaml
- inflated
