apiVersion: apps/v1
kind: Deployment
metadata:
  name: outbound-ingress-tunnel
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: server
        image: linuxserver/openssh-server
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - name: ssh
          containerPort: 2222
        - name: http-tunnel
          containerPort: 2080
        - name: https-tunnel
          containerPort: 2443
        env:
        - name: DOCKER_MODS
          value: "linuxserver/mods:openssh-server-ssh-tunnel"
        - name: PUBLIC_KEY_FILE
          value: "/var/run/secrets/ingress-tunnel/key.pub"
        - name: TZ
          value: "Europe/Paris" # {"$kpt-set":"timezone"}
        - name: SUDO_ACCESS
          value: "true"
        - name: USER_NAME
          value: "nxmatic" # {"$pkt-set":"username"}
        volumeMounts:
        - name: public-key
          mountPath: "/var/run/secrets"
      volumes:
      - name: public-key
        secret:
          secretName: ingress-tunnel
          items:
          - key: public-key
            path: ingress-tunnel/key.pub
---
apiVersion: v1
kind: Service
metadata:
  name: outbound-ingress-tunnel
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ingress-nxmatic.jxlabs-nos-master.build-jx-prod.build.nuxeo.com # {"$kpt-set":"hostname-binding"}
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    name: https-tunnel
    targetPort: 2443
  - protocol: TCP
    port: 22
    name: ssh
    targetPort: 2222
