apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gcp-auth-certs
  namespace: metadata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gcp-auth-certs
subjects:
  - kind: ServiceAccount
    name: gcp-auth-certs
    namespace: gcp-auth
