apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  name: metrics-server
  component: monitoring
  part-of: kubernetes
namespace: metrics
resources:
- inventory.yaml
- namespace.yaml
- release
patchesJson6902:
- target:
    version: v1
    kind: Deployment
    namespace: kube-system
    name: metrics-server
  patch: |- 
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --kubelet-insecure-tls
