apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  partOf: jx3-on-premise
namespace: nxmatic
resources:
  - inventory.yaml
components:
  - ../../network/ingress-tunnel/outbound
