apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
commonLabels:
  name: inbound-ingress-tunnel
  component: network
resources:
- inbound-deployment.yaml
secretGenerator:
- name: ingress-tunnel
  type: opaque
  behavior: merge
  literals:
  - load-balancer=172.18.0.129
components:
- ../config
