kind: ClusterRoleBinding # Source: csi-hostpath/templates/rbac-csi-snapshotter.yaml
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-snapshotter-role
subjects:
- kind: ServiceAccount
  name: csi-snapshotter
  # replace with non-default namespace name
  namespace: csi-system
roleRef:
  kind: ClusterRole
  # change the name also here if the ClusterRole gets renamed
  name: external-snapshotter-runner
  apiGroup: rbac.authorization.k8s.io
