# Resizer must be able to work with end point in current namespace
# if (and only if) leadership election is enabled
kind: Role # Source: csi-hostpath/templates/external-resizer-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # replace with non-default namespace name
  namespace: csi-system
  name: external-resizer-cfg
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
