kind: RoleBinding # Source: csi-hostpath/templates/external-provisioner-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-role-cfg
  # replace with non-default namespace name
  namespace: csi-system
subjects:
- kind: ServiceAccount
  name: csi-provisioner
  # replace with non-default namespace name
  namespace: csi-system
roleRef:
  kind: Role
  name: external-provisioner-cfg
  apiGroup: rbac.authorization.k8s.io
