kind: Role # Source: csi-hostpath/templates/rbac-csi-snapshotter.yaml
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: csi-system # TODO: replace with the namespace you want for your sidecar
  name: external-snapshotter-leaderelection
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
