kind: RoleBinding # Source: csi-hostpath/templates/rbac-csi-snapshotter.yaml
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-snapshotter-leaderelection
  namespace: csi-system # TODO: replace with the namespace you want for your sidecar
subjects:
- kind: ServiceAccount
  name: csi-snapshotter
  namespace: csi-system # TODO: replace with the namespace you want for your sidecar
roleRef:
  kind: Role
  name: external-snapshotter-leaderelection
  apiGroup: rbac.authorization.k8s.io
